// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rhupuikoqlzsitmtcdaz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJodXB1aWtvcWx6c2l0bXRjZGF6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2OTc5NTksImV4cCI6MjA2NjI3Mzk1OX0.Jjd_i2UUn4PG6fud-CyEEV_dFF9pR27u46R6FAomk5w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);